spring.application.name=api-totvs
#spring.cloud.azure.storage.blob.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
#spring.cloud.azure.storage.blob.endpoint=${AZURE_STORAGE_ACCOUNT_ENDPOINT}

spring.datasource.url=jdbc:postgresql://localhost/mydatabase?createDatabaseIfNotExist=true
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update